<?php
return [
    'name' => 'BillX',
    'version' => '1.0.0',
    'description' => 'On-the-go bill and receipt generator',
    'database' => [
        'host' => 'localhost',
        'port' => '3306',
        'database' => 'mmb_billx',
        'username' => 'root',
        'password' => '',
    ],
    'bill_types' => [
        'fuel'       => 'Fuel Bill',
        'driver'     => 'Driver Salary',
        'helper'     => 'Daily Helper Bill',
        'rent'       => 'Rent Receipt',
        'book'       => 'Book Invoice',
        'internet'   => 'Internet Invoice',
        'restaurant' => 'Restaurant Bill',
        'lta'        => 'LTA Receipt',
        'ecom'       => 'E-Com Invoice',
        'general'    => 'General Bill',
        'recharge'   => 'Recharge Receipt',
        'medical'    => 'Medical Bill',
        'stationary' => 'Stationary Bill',
        'cab'        => 'Cab & Travel Bill',
        'mart'       => 'Mart Bill',
        'gym'        => 'Gym Bill',
        'hotel'      => 'Hotel Bill',
        'newspaper'  => 'News Paper Bill',
    ],
    // Primary accent colour per bill type — used by PHP view templates.
    // The matching JS colour map in generate.php must stay in sync manually.
    'bill_colors' => [
        'fuel'       => '#e65000',
        'driver'     => '#1565c0',
        'helper'     => '#546e7a',
        'rent'       => '#6a1b9a',
        'book'       => '#5d4037',
        'internet'   => '#0277bd',
        'restaurant' => '#c62828',
        'lta'        => '#2e7d32',
        'ecom'       => '#1565c0',
        'general'    => '#37474f',
        'recharge'   => '#00838f',
        'medical'    => '#0077b6',
        'stationary' => '#bf360c',
        'cab'        => '#e65100',
        'mart'       => '#1b5e20',
        'gym'        => '#212121',
        'hotel'      => '#7d5a00',
        'newspaper'  => '#1a1a1a',
    ],
    // Layout group for each bill type — determines which print template is used.
    'bill_groups' => [
        'restaurant' => 'thermal',
        'recharge'   => 'thermal',
        'mart'       => 'thermal',
        'newspaper'  => 'thermal',
        'driver'     => 'payslip',
        'helper'     => 'payslip',
        'fuel'       => 'fuel',
        'cab'        => 'cab',
        'rent'       => 'official',
        'lta'        => 'official',
        'medical'    => 'medical',
        'hotel'      => 'hotel',
        'gym'        => 'gym',
        'book'       => 'invoice',
        'internet'   => 'invoice',
        'ecom'       => 'invoice',
        'general'    => 'invoice',
        'stationary' => 'invoice',
    ],
];
