<?php
/**
 * CardX Project Configuration
 *
 * @package MMB\Projects\IDCard
 */

return [
    'name'        => 'CardX',
    'version'     => '2.0.0',
    'description' => 'AI-powered professional ID card generator with templates',

    'database' => [
        'host'     => 'localhost',
        'port'     => '3306',
        'database' => 'mmb_idcard',
        'username' => 'root',
        'password' => '',
    ],

    // =========================================================================
    // Built-in template definitions
    // orientation: 'landscape' (85.6×54 mm)  |  'portrait' (54×85.6 mm)
    // =========================================================================
    'templates' => [

        // ── HORIZONTAL / LANDSCAPE ────────────────────────────────────────────

        'corporate' => [
            'name'        => 'Corporate',
            'description' => 'Clean corporate employee ID card',
            'color'       => '#1e40af',
            'accent'      => '#3b82f6',
            'bg'          => '#ffffff',
            'text'        => '#1e293b',
            'orientation' => 'landscape',
            'fields'      => ['name','company_name','company_address','designation','department','employee_id','dob','phone','email','photo'],
            'logo'        => true,
        ],
        'student' => [
            'name'        => 'Student',
            'description' => 'University / school student ID card',
            'color'       => '#065f46',
            'accent'      => '#10b981',
            'bg'          => '#ffffff',
            'text'        => '#064e3b',
            'orientation' => 'landscape',
            'fields'      => ['name','school_name','school_address','course','roll_number','year','dob','phone','email','photo'],
            'logo'        => true,
        ],
        'event' => [
            'name'        => 'Event',
            'description' => 'Conference / event attendee badge',
            'color'       => '#7c3aed',
            'accent'      => '#a78bfa',
            'bg'          => '#1e1b4b',
            'text'        => '#f5f3ff',
            'orientation' => 'landscape',
            'fields'      => ['name','company_name','title','event_name','badge_id','phone','email','photo'],
            'logo'        => true,
        ],
        'visitor' => [
            'name'        => 'Visitor',
            'description' => 'Visitor / guest pass',
            'color'       => '#b45309',
            'accent'      => '#f59e0b',
            'bg'          => '#fffbeb',
            'text'        => '#92400e',
            'orientation' => 'landscape',
            'fields'      => ['name','company_name','host_name','purpose','visit_date','expiry_date','badge_id','phone','photo'],
            'logo'        => true,
        ],
        'medical' => [
            'name'        => 'Medical Staff',
            'description' => 'Hospital / clinic staff ID card',
            'color'       => '#0369a1',
            'accent'      => '#0ea5e9',
            'bg'          => '#f0f9ff',
            'text'        => '#0c4a6e',
            'orientation' => 'landscape',
            'fields'      => ['name','company_name','company_address','designation','department','license_no','dob','phone','email','blood_group','photo'],
            'logo'        => true,
        ],
        'tech' => [
            'name'        => 'Tech Company',
            'description' => 'Modern tech startup employee ID',
            'color'       => '#0891b2',
            'accent'      => '#22d3ee',
            'bg'          => '#0f172a',
            'text'        => '#e0f2fe',
            'orientation' => 'landscape',
            'fields'      => ['name','company_name','designation','department','employee_id','phone','email','photo'],
            'logo'        => true,
        ],
        'bank' => [
            'name'        => 'Banking / Finance',
            'description' => 'Bank or financial institution employee',
            'color'       => '#1e3a5f',
            'accent'      => '#c9a84c',
            'bg'          => '#ffffff',
            'text'        => '#1e293b',
            'orientation' => 'landscape',
            'fields'      => ['name','company_name','company_address','designation','branch','employee_id','dob','phone','email','photo'],
            'logo'        => true,
        ],
        'media' => [
            'name'        => 'Press / Media',
            'description' => 'Journalist / media press credential',
            'color'       => '#dc2626',
            'accent'      => '#f87171',
            'bg'          => '#ffffff',
            'text'        => '#1e293b',
            'orientation' => 'landscape',
            'fields'      => ['name','company_name','title','badge_id','nationality','phone','email','photo'],
            'logo'        => true,
        ],
        'govt' => [
            'name'        => 'Government',
            'description' => 'Government department employee ID',
            'color'       => '#14532d',
            'accent'      => '#22c55e',
            'bg'          => '#f0fdf4',
            'text'        => '#14532d',
            'orientation' => 'landscape',
            'fields'      => ['name','company_name','company_address','designation','department','employee_id','nationality','dob','phone','email','photo'],
            'logo'        => true,
        ],
        'security' => [
            'name'        => 'Security',
            'description' => 'Security personnel / guard ID',
            'color'       => '#1c1917',
            'accent'      => '#f59e0b',
            'bg'          => '#292524',
            'text'        => '#fafaf9',
            'orientation' => 'landscape',
            'fields'      => ['name','company_name','designation','badge_id','zone','dob','phone','blood_group','photo'],
            'logo'        => true,
        ],

        // ── VERTICAL / PORTRAIT ────────────────────────────────────────────────

        'corporate_v' => [
            'name'        => 'Corporate (V)',
            'description' => 'Vertical corporate employee ID – matching reference',
            'color'       => '#1e40af',
            'accent'      => '#3b82f6',
            'bg'          => '#ffffff',
            'text'        => '#1e293b',
            'orientation' => 'portrait',
            'fields'      => ['name','company_name','company_address','designation','department','employee_id','dob','blood_group','phone','email','photo'],
            'logo'        => true,
        ],
        'student_v' => [
            'name'        => 'Student (V)',
            'description' => 'Vertical student / university ID card',
            'color'       => '#065f46',
            'accent'      => '#10b981',
            'bg'          => '#ffffff',
            'text'        => '#064e3b',
            'orientation' => 'portrait',
            'fields'      => ['name','school_name','school_address','roll_number','course','year','dob','blood_group','phone','email','photo'],
            'logo'        => true,
        ],
        'hospital_v' => [
            'name'        => 'Hospital (V)',
            'description' => 'Vertical hospital / clinic staff ID',
            'color'       => '#0369a1',
            'accent'      => '#0ea5e9',
            'bg'          => '#f0f9ff',
            'text'        => '#0c4a6e',
            'orientation' => 'portrait',
            'fields'      => ['name','company_name','company_address','designation','department','license_no','dob','blood_group','phone','email','photo'],
            'logo'        => true,
        ],
        'event_v' => [
            'name'        => 'Event (V)',
            'description' => 'Vertical event / conference badge',
            'color'       => '#7c3aed',
            'accent'      => '#a78bfa',
            'bg'          => '#1e1b4b',
            'text'        => '#f5f3ff',
            'orientation' => 'portrait',
            'fields'      => ['name','company_name','title','event_name','badge_id','dob','phone','email','photo'],
            'logo'        => true,
        ],
        'visitor_v' => [
            'name'        => 'Visitor (V)',
            'description' => 'Vertical visitor / guest pass',
            'color'       => '#b45309',
            'accent'      => '#f59e0b',
            'bg'          => '#fffbeb',
            'text'        => '#92400e',
            'orientation' => 'portrait',
            'fields'      => ['name','company_name','host_name','purpose','visit_date','expiry_date','badge_id','phone','photo'],
            'logo'        => true,
        ],
        'govt_v' => [
            'name'        => 'Government (V)',
            'description' => 'Vertical government department ID',
            'color'       => '#14532d',
            'accent'      => '#22c55e',
            'bg'          => '#f0fdf4',
            'text'        => '#14532d',
            'orientation' => 'portrait',
            'fields'      => ['name','company_name','company_address','designation','department','employee_id','nationality','dob','blood_group','phone','email','photo'],
            'logo'        => true,
        ],
        'ngo_v' => [
            'name'        => 'NGO / Non-Profit (V)',
            'description' => 'Vertical NGO volunteer / staff ID',
            'color'       => '#7c3aed',
            'accent'      => '#a78bfa',
            'bg'          => '#ffffff',
            'text'        => '#1e293b',
            'orientation' => 'portrait',
            'fields'      => ['name','company_name','company_address','title','employee_id','nationality','dob','phone','email','photo'],
            'logo'        => true,
        ],
        'library_v' => [
            'name'        => 'Library Card (V)',
            'description' => 'Vertical library membership card',
            'color'       => '#92400e',
            'accent'      => '#f59e0b',
            'bg'          => '#fffbeb',
            'text'        => '#92400e',
            'orientation' => 'portrait',
            'fields'      => ['name','school_name','school_address','roll_number','course','expiry_date','dob','phone','photo'],
            'logo'        => true,
        ],
        'gym_v' => [
            'name'        => 'Gym / Fitness (V)',
            'description' => 'Vertical gym / sports club membership',
            'color'       => '#dc2626',
            'accent'      => '#f87171',
            'bg'          => '#0f172a',
            'text'        => '#f1f5f9',
            'orientation' => 'portrait',
            'fields'      => ['name','company_name','badge_id','dob','blood_group','expiry_date','phone','photo'],
            'logo'        => true,
        ],
        'transport_v' => [
            'name'        => 'Transport (V)',
            'description' => 'Vertical driver / transport staff ID',
            'color'       => '#1c1917',
            'accent'      => '#f59e0b',
            'bg'          => '#ffffff',
            'text'        => '#1e293b',
            'orientation' => 'portrait',
            'fields'      => ['name','company_name','company_address','designation','license_no','dob','expiry_date','phone','blood_group','photo'],
            'logo'        => true,
        ],
        'university_v' => [
            'name'        => 'University Faculty (V)',
            'description' => 'Vertical university faculty / staff ID',
            'color'       => '#0891b2',
            'accent'      => '#22d3ee',
            'bg'          => '#f0f9ff',
            'text'        => '#0c4a6e',
            'orientation' => 'portrait',
            'fields'      => ['name','company_name','company_address','designation','department','employee_id','dob','phone','email','photo'],
            'logo'        => true,
        ],
        'security_v' => [
            'name'        => 'Security Guard (V)',
            'description' => 'Vertical security / guard personnel ID',
            'color'       => '#1c1917',
            'accent'      => '#f59e0b',
            'bg'          => '#292524',
            'text'        => '#fafaf9',
            'orientation' => 'portrait',
            'fields'      => ['name','company_name','company_address','designation','badge_id','zone','rank','dob','blood_group','phone','photo'],
            'logo'        => true,
        ],
        'retail_v' => [
            'name'        => 'Retail / Shop (V)',
            'description' => 'Vertical retail store / shop staff ID',
            'color'       => '#7c3aed',
            'accent'      => '#a78bfa',
            'bg'          => '#ffffff',
            'text'        => '#1e293b',
            'orientation' => 'portrait',
            'fields'      => ['name','company_name','company_address','designation','employee_id','department','shift','dob','phone','photo'],
            'logo'        => true,
        ],
    ],

    // =========================================================================
    // Field labels for the generator form
    // =========================================================================
    'field_labels' => [
        'name'              => 'Full Name',
        'designation'       => 'Designation / Job Title',
        'department'        => 'Department',
        'employee_id'       => 'Employee ID',
        'roll_number'       => 'Roll / Enrollment No.',
        'course'            => 'Course / Program',
        'year'              => 'Year / Batch',
        'event_name'        => 'Event Name',
        'badge_id'          => 'Badge / Pass ID',
        'host_name'         => 'Host Name',
        'purpose'           => 'Purpose of Visit',
        'visit_date'        => 'Visit Date',
        'title'             => 'Title / Role',
        'organization'      => 'Organization / Company',
        'id_number'         => 'ID Number',
        'license_no'        => 'License / Reg. No.',
        'blood_group'       => 'Blood Group',
        'phone'             => 'Phone / Mobile',
        'email'             => 'Email Address',
        'photo'             => 'Photo',
        // New professional fields
        'company_name'      => 'Company / Organisation Name',
        'company_address'   => 'Company Address',
        'school_name'       => 'School / College Name',
        'school_address'    => 'School / College Address',
        'dob'               => 'Date of Birth',
        'expiry_date'       => 'Expiry Date',
        'valid_from'        => 'Valid From',
        'valid_till'        => 'Valid Till',
        'nationality'       => 'Nationality',
        'branch'            => 'Branch / Division',
        'shift'             => 'Shift / Timing',
        'session'           => 'Academic Session',
        'reg_number'        => 'Registration No.',
        'zone'              => 'Zone / Area',
        'rank'              => 'Rank / Grade',
        'gender'            => 'Gender',
        'joining_date'      => 'Joining Date',
    ],
];
